implement simple tab navigation
mate-academy/react_tabs pull request #1054
Opened 2022-09-12 13:58 UTC by tiserett

[DEMO LINK](https://tiserett.github.io/react_tabs/)

2022-09-12 16:11 UTC, Dmytro-Matsehora approved these changes
Great job! 🚀

2022-09-13 09:45 UTC, AlinaMatuschak requested changes
Good work 🔥. Just small issues

2022-09-13 09:45 UTC, AlinaMatuschak commented on src/components/Tabs/Tabs.tsx
> +              }
use [classnames](https://www.npmjs.com/package/classnames)

2022-09-13 18:00 UTC, AlinaMatuschak approved these changes

2024-03-09 11:06 UTC, closed without merging