create Tabs component, added render and styles logic
mate-academy/react_tabs pull request #1155
Opened 2022-10-23 15:18 UTC by SerhiiRomaniukWD

[DEMO LINK](https://serhiiromaniukwd.github.io/react_tabs/)

2022-11-03 12:38 UTC, xiimiik approved these changes
GJ 🔥

2022-11-03 16:06 UTC, sergii-nosachenko requested changes

2022-11-03 16:06 UTC, sergii-nosachenko commented on src/react-app-env.d.ts
> +}
```suggestion
```
Move types to separate files.

2022-11-03 16:06 UTC, sergii-nosachenko commented on src/components/Tabs/Tabs.tsx
> +                onFocus={() => selectedTabId !== id && onTabSelected(tab)}
Improper event used. Now it fires on Tab key click (try it in browser). Use click event.

2022-11-03 16:06 UTC, sergii-nosachenko commented on src/components/Tabs/Tabs.tsx
> +                onFocus={() => selectedTabId !== id && onTabSelected(tab)}
Create separate handler that accepts `tab` as argument and decides what to do next. Move your logic there.

2022-11-08 07:44 UTC, Andr1yK approved these changes

2025-05-25 17:09 UTC, closed without merging