solution
mate-academy/react_tabs pull request #1213
Opened 2022-11-13 20:35 UTC by savchuksavchuk

[DEMO LINK](https://savchuksavchuk.github.io/react_tabs/)

2022-11-14 19:38 UTC, polosanya requested changes
Almost done! Please pay attention to my comments

2022-11-14 19:38 UTC, polosanya commented on src/App.tsx
> +        {selectedTab.title}
```suggestion
        {`Selected tab is ${selectedTab.title}`}
```

2022-11-14 19:38 UTC, polosanya commented on src/components/Tabs/Tabs.tsx
> +                onClick={(event) => {
Move it to the separate function

2022-11-15 15:48 UTC, loralevitska requested changes
great! need some improvements

2022-11-15 15:48 UTC, loralevitska commented on src/components/Tabs/Tabs.tsx
> +    isSelected: Tab,
the variable `is...`  says that there will be a boolean value, and there will be a number, looks confusing. Rename the variable to a more relevant name. Read about [boolean naming](https://dev.to/michi/tips-on-naming-boolean-variables-cleaner-code-35ig) for better understanding

2022-11-16 10:56 UTC, Anastasiia-Svintsova approved these changes

2022-11-16 10:56 UTC, Anastasiia-Svintsova commented on src/components/Tabs/Tabs.tsx
> +        </ul>
Would be great to move the list and item elements to separate files

2024-12-28 10:52 UTC, closed without merging