Develop
mate-academy/react_tabs pull request #1371
Opened 2023-01-22 18:07 UTC by kenvastolord

[DEMO LINK](https://kenvastolord.github.io/react_tabs/)

2023-01-23 11:18 UTC, CharAnagn requested changes
For the second test that you are failing, if you look at the tests it passes a selectedTabId to your Tabs component that doesn't match with any tab. So you need to find a way that you'll search for the tab that has the selectedTabId and if you don't find one, instead of returning undefined you should select the first tab.

2023-01-23 11:18 UTC, CharAnagn commented on src/components/Tabs/Tabs.tsx
> +                  onTabSelected(tab.id);
Here the tests require to pass the tab as an argument and not the tab.id

2023-01-23 11:18 UTC, CharAnagn commented on src/App.tsx
> +        ))}
I would suggest to create a variable and use the find method to find the tab that you are looking for based on the id.

2023-01-26 12:23 UTC, naziamoff approved these changes
well done. Just one suggestion

2023-01-26 12:23 UTC, naziamoff commented on src/App.tsx
> +  const handleSelectedTab = (tab: Tab) => setSelectedTabId(tab.id);
you are passing the tab to this component anyway. So there's no need to get the tab by id, you can just store the whole tab to your state

2026-05-19 08:11 UTC, closed without merging