Solution by DK
mate-academy/react_tabs pull request #1497
Opened 2023-03-22 21:50 UTC by DimaK123

[DEMO LINK](https://Dimak123.github.io/react_tabs/)

2023-03-23 08:12 UTC, polosanya requested changes
Let's improve your code a bit)

2023-03-23 08:12 UTC, polosanya commented on src/App.tsx
> +  const onTabSelected = (tab: Tab) => {
```suggestion
  const handleTabSelected = (tab: Tab) => {
```
https://javascript.plainenglish.io/handy-naming-conventions-for-event-handler-functions-props-in-react-fc1cbb791364

2023-03-23 08:12 UTC, polosanya commented on src/components/Tabs/Tabs.tsx
> +                  className={classNames({ 'is-active': selectedTabId === id })}
Compare it with the currentTab.id

2023-03-23 08:12 UTC, polosanya commented on src/components/Tabs/Tabs.tsx
> +                  <a href={`#${id}`} data-cy="TabLink" onClick={() => currentTab !== tab && onTabSelected(tab)}>
```suggestion
                  <a 
                    href={`#${id}`} 
                    data-cy="TabLink" 
                    onClick={() => currentTab !== tab && onTabSelected(tab)}
                  >
```
Also, don't compare objects like that
![image](https://user-images.githubusercontent.com/96409563/227142033-e855c3bf-b688-411c-ba4c-1a55ee7ff861.png)

2023-03-23 08:12 UTC, polosanya commented on src/App.tsx
> +      setSelectedTabId(tabs[0].id);
You already check it when finding a tab, so there is actually no need to double check

2023-03-23 08:12 UTC, polosanya commented on src/components/Tabs/Tabs.tsx
> +    const currentTab = tabs.find(tab => tab.id === selectedTabId) || tabs[0];
You do the same here and in App. 
You can create a helper function in order not to duplicate yourself

2023-03-23 20:41 UTC, DimaK123 commented on src/components/Tabs/Tabs.tsx
> +    const currentTab = tabs.find(tab => tab.id === selectedTabId) || tabs[0];
Thanks for the advice. I hope that I've done everything correctly, but unfortunately, the test still failed. I see the error message in the terminal.
Why onTabFinder is not a function ?


![изображение](https://user-images.githubusercontent.com/92954488/227352205-9bd831b6-0d10-420b-8d2d-454d5d1a6e7d.png)

2023-03-28 18:07 UTC, TarasHoliuk approved these changes
LGTM :+1:

2023-04-10 17:44 UTC, agniya-i approved these changes

2023-04-11 16:18 UTC, closed without merging