Develop react_tabs
mate-academy/react_tabs pull request #1510
Opened 2023-03-27 19:33 UTC by sergey-lipikhin

[DEMO LINK](https://sergey-lipikhin.github.io/react_tabs/)

2023-03-29 11:39 UTC, mstrilec approved these changes
GJ!

2023-03-31 11:04 UTC, illiarerun requested changes

2023-03-31 11:04 UTC, illiarerun commented on src/components/Tabs/Tabs.tsx
> +  const selectedTab = tabs.find(tab => tab.id === selectedTabId) || tabs[0];
you repeat this logic in App.tsx - create a function helper for it

2023-04-03 16:14 UTC, sergii-nosachenko approved these changes
Good work 👍
Commented

2023-04-03 16:14 UTC, sergii-nosachenko commented on src/App.tsx
>  export const tabs = [
```suggestion
export const tabs: Tab[] = [
```

2023-04-03 16:14 UTC, sergii-nosachenko commented on src/helpers.ts
> +export function getSelectedTab(tabs: Tab[], selectedTabId: string): Tab {
```suggestion
export function getSelectedTabById(tabs: Tab[], selectedTabId: string): Tab {
```

2024-03-20 11:26 UTC, closed without merging