add solution
mate-academy/react_tabs pull request #1701
Opened 2023-06-19 14:36 UTC by growingananas

[DEMO LINK](https://growingananas.github.io/react_tabs/)

2023-06-21 09:34 UTC, silchyn requested changes

2023-06-21 09:34 UTC, silchyn commented on src/App.tsx
> +  const [selectedTabTitle, setSelectedTabTitle] = useState('Tab 1');
So we just duplicate the logic everywhere?

2023-06-21 09:34 UTC, silchyn commented on src/App.tsx
> +  const [selectedTabTitle, setSelectedTabTitle] = useState('Tab 1');
There are some magic strings

2023-06-21 09:34 UTC, silchyn commented on src/components/Tabs/Tabs.tsx
> +    || tabs[0].id;
```suggestion
  const currentTabId = (tabs.find(tab => (
    tab.id === selectedTabId
  )) || tabs[0]).id;
```

2023-06-21 09:34 UTC, silchyn commented on src/components/Tabs/Tabs.tsx
> +                }}
Put it in a separate callback

2023-06-22 07:06 UTC, 33Orange approved these changes
Well done

2023-06-22 07:06 UTC, 33Orange commented on src/components/Tabs/Tabs.tsx
> +  const handleSelectedTab = (tab: Tab) => {
```suggestion
  const selectTab = (tab: Tab) => {
```

2023-10-26 13:02 UTC, closed without merging