Solution
mate-academy/react_tabs pull request #1710
Opened 2023-06-20 14:47 UTC by Shevtsooov

[DEMO LINK](https://Shevtsooov.github.io/react_tabs/)

2023-06-21 09:27 UTC, silchyn requested changes

2023-06-21 09:27 UTC, silchyn commented on src/App.tsx
> +  const [selectedTabId, setSelectedTabId] = useState(tabs[0]);
But `tab[0]` is not id

2023-06-21 09:27 UTC, silchyn commented on src/components/Tabs/Tabs.tsx
> +                }}
Put it in a separate callback

2023-06-23 06:48 UTC, 33Orange approved these changes
Good job

2023-06-23 06:48 UTC, 33Orange commented on src/components/Tabs/Tabs.tsx
> +  const handleClick = (tab: Tab) => {
This function is not a `handler` for click

```suggestion
  const selectTab = (tab: Tab) => {
```

2024-05-05 10:50 UTC, closed without merging