react_tabs-js-state
mate-academy/react_tabs pull request #1748
Opened 2023-06-27 20:01 UTC by vintwp

https://vintwp.github.io/react_tabs-js/

2023-07-24 18:20 UTC, nazarmatsevych requested changes
* test

2024-06-27 07:35 UTC, DarkMistyRoom approved these changes
Good job! Check the comments

2024-06-27 07:35 UTC, DarkMistyRoom commented on src/App.jsx
> +        }
better use interpolation

2024-06-27 07:35 UTC, DarkMistyRoom commented on src/components/Tabs/Tabs.jsx
> +                  }
move this logic to a handler function

2024-08-15 20:02 UTC, closed without merging