Solution
mate-academy/react_tabs pull request #240
Opened 2020-09-08 17:46 UTC by 1nsider21

- [DEMO LINK](https://1nsider21.github.io/react_tabs/)

2020-09-08 18:08 UTC, YuriiRysyn approved these changes

2020-09-09 06:24 UTC, irenhh requested changes

2020-09-09 06:24 UTC, irenhh commented on src/components/Tabs.jsx
> +  tabSelect = i => this.setState({ index: i });
if it is index, write `index`

2020-09-09 06:24 UTC, irenhh commented on src/components/Tabs.jsx
> +  tabs: PropTypes.arrayOf(PropTypes.object).isRequired,
describe object

2020-09-09 08:56 UTC, irenhh approved these changes

2023-08-22 11:53 UTC, closed without merging