solution
mate-academy/react_tabs pull request #328
Opened 2021-01-24 12:33 UTC by Layrovell

[DEMO LINK](https://Layrovell.github.io/react_tabs/)

2021-01-24 15:37 UTC, Serhii-Alieksieievych approved these changes

2021-01-26 14:30 UTC, aliceblunt8 requested changes

2021-01-26 14:30 UTC, aliceblunt8 commented on src/App.js
> +  handlerOnClick = (e) => {
```suggestion
 selectTab = (e) => {
```

2021-01-26 14:30 UTC, aliceblunt8 commented on src/components/Tab/Tab.css
> +/*.container {*/
delete empty files

2021-01-26 14:30 UTC, aliceblunt8 commented on src/components/Tab/Tab.jsx
> +  return (
```suggestion
export const Tab = ({ tabs, active, handlerOnClick }) => (
```

2021-01-26 14:30 UTC, aliceblunt8 commented on src/components/Tab/Tab.jsx
> +          )}
render this in App

2021-01-26 14:30 UTC, aliceblunt8 commented on src/App.js
> +    active: 'Tab 1',
save selected tab in here

2021-01-26 14:30 UTC, aliceblunt8 commented on src/components/Tab/Tab.jsx
> +          }}
```suggestion
          onClick={() =>handlerOnClick(tab.title)}
```

2021-01-27 08:55 UTC, aliceblunt8 requested changes

2021-01-27 08:55 UTC, aliceblunt8 commented on src/App.js
> +          handlerOnClick={this.selectTab}
```suggestion
          selectTab={this.selectTab}
```

2021-01-27 08:55 UTC, aliceblunt8 commented on src/App.js
> +    active: this.selectTab,
I meant not this)) now you save object method in state, but I meant to save active tab (object) or it's index (number) in App's state

2021-01-27 08:55 UTC, aliceblunt8 commented on src/App.js
> +            .map(tab => <p>{tab.content}</p>)}
if you save selected tab's index in state you won't need to filter tabs in order to find one
you can just `tabs[this.state.selectedTabIndex].content`

2021-01-27 08:55 UTC, aliceblunt8 commented on src/components/Tab/Tab.jsx
> +        onClick={() => handlerOnClick(tab.title)}
I think it's better to pass index, not title

2021-01-27 10:59 UTC, aliceblunt8 approved these changes

2021-01-27 10:59 UTC, aliceblunt8 commented on src/App.js
> +    active: 0,
```suggestion
    activeTabId: 0,
```

2021-01-27 10:59 UTC, aliceblunt8 commented on src/components/Tab/Tab.jsx
> +        className={active === idx ? 'active' : ''}
you can use classnames lib
https://www.npmjs.com/package/classnames

2024-05-21 11:26 UTC, closed without merging