solution
mate-academy/react_tabs pull request #577
Opened 2021-09-15 12:52 UTC by RomSmile

DEMO LINK https://RomSmile.github.io/react_tabs/

2021-09-17 19:20 UTC, MaksymBeliever approved these changes

2021-09-17 19:20 UTC, MaksymBeliever commented on src/App.tsx
> +    selectedTab: 'tab-1',
Ти захардкодив value для `selectedTab`, якщо масив `tabs` оновиться, наприклад там може змінитись текст для табів, в такому разі в тебе і надалі залишатиметься value `tab-1`

2021-09-17 19:20 UTC, MaksymBeliever commented on src/App.tsx
> +        <Content selectedTab={this.state.selectedTab} tabButtons={tabs} />
Навіщо тобі стільки різних компонентів? Тут же доволі проста функціональність, не впевнений, що в поточному завданні його потрібно так розділяти

2021-09-17 19:41 UTC, MaksymBeliever approved these changes
Додай ще трохи стилів то табів

2021-09-20 07:40 UTC, Elena-brv requested changes

2021-09-20 07:40 UTC, Elena-brv commented on src/App.tsx
> +  state = {
```suggestion
  state: State = {
```

2021-09-20 07:40 UTC, Elena-brv commented on src/components/Buttons.tsx
> +        return (
avoid return

2021-09-20 07:40 UTC, Elena-brv commented on src/App.tsx
> +    selectedTab: 'tab-1',
and if it's id, call it selectedTabId

2021-09-20 07:40 UTC, Elena-brv commented on src/components/Content.tsx
> +      {currentTab === undefined ? '' : currentTab.content}
```suggestion
      {currentTab && currentTab.content}
```

2021-09-20 07:40 UTC, Elena-brv commented on src/components/Buttons.tsx
> +            onClick={() => changeTab(tab.id)}
![image](https://user-images.githubusercontent.com/64437769/133969922-a8c9cc27-4c0e-487d-a624-201bcfec5852.png)

2021-09-21 11:23 UTC, Elena-brv commented on src/App.tsx
> +    selectedTab: tabs[0].id,
```suggestion
    selectedTabId: tabs[0].id,
```

2021-09-21 11:28 UTC, Elena-brv requested changes

2021-09-21 11:28 UTC, Elena-brv commented on src/components/Buttons.tsx
> +          onClick={() => changeTab(tab.id)}
you still call callback every time on clicking the tab (even if this tab is already opened)
![image](https://user-images.githubusercontent.com/64437769/134162676-947af27f-cc01-47e1-a548-54a8b4f89ee0.png)

2021-09-21 11:28 UTC, Elena-brv commented on src/components/Content.tsx
> +  );
```suggestion
  return currentTab && currentTab.content;
```

2023-10-17 08:29 UTC, closed without merging