Done
mate-academy/react_tabs pull request #715
Opened 2022-01-26 15:08 UTC by MaksimusCRS

[DEMO LINK](https://MaksimusCRS.github.io/react_tabs/)

2022-01-26 21:11 UTC, HrynykNataliia requested changes
+не треба додавати лишні файли до пул реквесту (наприклад: LICENSE)

2022-01-26 21:11 UTC, HrynykNataliia commented on src/components/Tabs/Tabs.tsx
> +  selectedTab: Tab,
Pass the selectedTabId as a prop to the Tabs, the specified tab should be selected if possible (otherwise the first tab is selected)

2022-01-27 01:03 UTC, MaksimusCRS commented on src/components/Tabs/Tabs.tsx
> +  selectedTab: Tab,
Уже исправил, но профита в этом действии не вижу, наоборот, дополнительная работа появилась из-за этого действия)

2022-01-27 11:37 UTC, HrynykNataliia approved these changes

2022-01-31 14:58 UTC, Elena-brv approved these changes

2022-01-31 14:58 UTC, Elena-brv commented on src/App.tsx
> +          {`Selected Tab is: ${this.state.selectedTab.title}`}
use destructuring

2022-01-31 14:58 UTC, Elena-brv commented on src/components/Tabs/Tabs.tsx
> +    || props.tabs[0];
```suggestion
  const findSelectedTab = () => (
    props.tabs.find(tab => tab.id === props.selectedTabId)
    || props.tabs[0]
  );
```

2022-10-20 17:44 UTC, closed without merging