Created tabs
mate-academy/react_tabs pull request #775
Opened 2022-03-15 10:17 UTC by jursylian

[DEMO LINK](https://jursylian.github.io/react_tabs/)

2022-03-15 10:27 UTC, AndryKK approved these changes
Ти крута, гарно оформлено та креативно)
Ніби все працює нормально, апруваю.

2022-03-15 10:27 UTC, AndryKK commented on src/components/Tabs/Tabs.tsx
> +                className={selectedTabId === item.id
було б класно використати бібліотеку className, хоча я теж її ще не використав у своїй роботі.

2022-03-15 10:53 UTC, Elena-brv requested changes
красиво оформлено 🔥 
но так как вы уже прошли хуки, то давай переделаем это задание на хуках, а не на классовых компонентах

2022-03-16 12:39 UTC, Elena-brv requested changes
заголовок уехал, лучше поправить
<img width="1204" alt="image" src="https://user-images.githubusercontent.com/64437769/158591179-a57d9bbf-ba2a-4506-937b-1f22c10883be.png">

2022-03-16 12:39 UTC, Elena-brv commented on src/components/Tabs/Tabs.tsx
> +                  item !== selectedTab ? onTabSelected(item) : null
нельзя сравнивать объекты, это небезопасно, сравнивай табы по id,
так же лучше использовать if, тернарный оператор чаще используется для присвоения значения

2022-03-16 12:39 UTC, Elena-brv commented on src/components/Tabs/Tabs.tsx
> +                className={selectedTabId === item.id
да, используй classnames, в реальных проектах она так же часто используется 
https://github.com/JedWatson/classnames

2022-03-16 14:41 UTC, Elena-brv approved these changes

2022-03-16 14:41 UTC, Elena-brv commented on src/components/Tabs/Tabs.tsx
> +                  : 'button is-success')}
```suggestion
                className={classNames(
                  'button',
                  { 
                    'my-active': selectedTabId === item.id,
                    'is-success': selectedTabId !== item.id
                  }
                )}
```

2022-04-06 14:32 UTC, closed without merging