implement tabs component
mate-academy/react_tabs pull request #829
Opened 2022-05-16 12:41 UTC by misha200119

[DEMO LINK](https://misha200119.github.io/react_tabs/)

2022-05-16 15:52 UTC, lem47 approved these changes
Good work!

2022-05-17 08:31 UTC, MaksimusCRS requested changes

2022-05-17 08:31 UTC, MaksimusCRS commented on src/App.tsx
> +  const [selectedTab, setSelectedTab] = useState(tabs[0]);
Код сейчас не стабилен, ты должен обрабатывать вариант, когда tabs будет пустой, или его вообще не будет, в будущем все твои данные будут приходить с сервера и там могут возникать случаи, когда ответ не дошел

2022-05-17 08:31 UTC, MaksimusCRS commented on src/App.tsx
> +    const newSelectedTab = tabs.find(tab => tab.id === tabId) || tabs[0];
Тоже самое тут, а если tabs пустой массив?

2022-05-17 08:31 UTC, MaksimusCRS commented on src/components/Tabs/Tabs.tsx
> +      </div>
Есть смысл рендерить этот блок только есть ты нашел свой tab

2022-05-19 10:19 UTC, MaksimusCRS requested changes

2022-05-19 10:19 UTC, MaksimusCRS commented on src/App.tsx
> +  const [selectedTab, setSelectedTab] = useState(tabs[0]);
Этот коммент попал в немилость?)

2022-05-19 10:19 UTC, MaksimusCRS commented on src/App.tsx
> +  const [selectedTab, setSelectedTab] = useState(tabs[0]);
Ты задаешь tabs[0] в свой стейт, у тебя будут сыпаться ошибки, если его не будет

2022-05-19 10:24 UTC, misha200119 commented on src/App.tsx
> +  const [selectedTab, setSelectedTab] = useState(tabs[0]);
я делаю условный рендеринг в аппе, если у меня первый елемент что по дефолту будет undefined - тернарный оператор отрендерит заголовок с надписью что массив пуст

2022-05-19 10:49 UTC, MaksimusCRS approved these changes
:fire

2025-08-10 12:48 UTC, closed without merging