Solution
mate-academy/react_tabs pull request #845
Opened 2022-05-17 20:56 UTC by YegorKochetkov

[DEMO LINK](https://YegorKochetkov.github.io/react_tabs/)

2022-05-18 14:43 UTC, maxxnikiforov approved these changes
On my opinion all nice!

2022-05-19 08:25 UTC, MaksimusCRS requested changes

2022-05-19 08:25 UTC, MaksimusCRS commented on src/App.tsx
> +  const [selectedTab, setSelectedTab] = useState(tabs[0]);
А если tabs придет пустой с сервера или вообще не придет, что будет?

2022-05-19 08:25 UTC, MaksimusCRS commented on src/App.tsx
> +      />
Рендерь этот блок только если есть элементы в масиве

2022-05-19 08:25 UTC, MaksimusCRS commented on src/components/Tabs/Tabs.tsx
> +            </p>
Есть смысл рендерить этот блок только если у тебя есть контент

2022-05-19 11:09 UTC, MaksimusCRS approved these changes

2022-11-29 11:16 UTC, closed without merging