Solution
mate-academy/react_tabs pull request #910
Opened 2022-06-22 19:08 UTC by PRO-GRAM-MER

[DEMO](https://pro-gram-mer.github.io/react_tabs/)

2022-07-04 07:26 UTC, ihor-jpeg requested changes

2022-07-04 07:26 UTC, ihor-jpeg commented on src/App.tsx
> +        selectTab={selectTab}
```suggestion
        onSelectTab={handleSelectTab}
```

2022-07-04 07:26 UTC, ihor-jpeg commented on src/Tabs.tsx
> +  selectTab: (tab: Tab) => void;
can you simply pass an id here, not the entire tab?

2022-07-04 07:26 UTC, ihor-jpeg commented on src/Tabs.tsx
> +  )?.content;
useMemo

2022-07-04 07:26 UTC, ihor-jpeg commented on src/App.tsx
> +  };
useCallback

2022-07-06 07:24 UTC, VinnieJ-2k20 requested changes
DEMO LINK is not working, probably because you try to use object as JSX child in `Tabs.tsx` line 33.

2022-07-06 07:24 UTC, VinnieJ-2k20 commented on src/Tabs.tsx
> +        {tabClicked}
This seems to be a problem.

2022-07-07 07:17 UTC, VinnieJ-2k20 approved these changes

2026-03-29 20:35 UTC, closed without merging