first commit
mate-academy/react_tabs pull request #965
Opened 2022-07-21 21:41 UTC by khrystyna-sabat

[DEMO LINK](https://khrystyna-sabat.github.io/react_tabs/)

2022-07-22 07:28 UTC, k0nstrukt-or approved these changes
Well done!

2022-07-22 07:59 UTC, illiarerun requested changes

2022-07-22 07:59 UTC, illiarerun commented on src/App.tsx
> +          ${selectedTab.title}`}
you can write in one line

2022-07-22 07:59 UTC, illiarerun commented on src/components/Tabs/Tabs.tsx
> +              )}
you already have this logic in parent handler
```suggestion
                onTabSelected(tab)
              )}
```

2022-07-25 09:40 UTC, mykola-koval commented on src/App.tsx
> +import { Tab } from './types/Tab';
you can also store types in react-app.env.d.ts and use them without imports

2022-11-21 15:51 UTC, closed without merging